source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'
gem 'active_model_serializers'
gem 'bcrypt'
gem "mysql2"
gem 'composite_primary_keys'

group :test do
  # Use RSpec for specs
  gem 'rspec-rails'
  # Use Factory Girl for generating random test data
  gem 'factory_girl_rails'
  gem 'rspec-request_describer'
  gem 'database_rewinder'
  gem 'autodoc'
  gem 'json_spec'
  gem 'guard-rspec'
  gem 'sqlite3'
end

group :development do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end


